---
_extends: .github

repository:
  name: toxins
  description: A collection of small programs using toxcore.
  topics: toxcore

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - CodeFactor
          - Travis CI - Pull Request
          - code-review/reviewable
