---
_extends: template

repository:
  name: toxins
  description: A collection of small programs using toxcore.
  topics: toxcore
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - CodeFactor
          - Travis CI - Pull Request
          - WIP
          - code-review/reviewable
          - license/cla
